# Generated by Django 5.2.6 on 2025-10-13 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('url', models.TextField(verbose_name='Ссылка')),
                ('type', models.SmallIntegerField(choices=[(0, 'Простая'), (1, 'Сложная'), (2, 'Авито'), (3, 'Яндекс'), (4, 'Циан')], default=0, verbose_name='Тип')),
                ('status', models.SmallIntegerField(choices=[(0, '--------'), (1, 'Успешно'), (2, 'Ошибка'), (3, 'Доступен')], default=0, verbose_name='Статус')),
                ('status_changed', models.DateTimeField(default=None, null=True, verbose_name='Статус изменился')),
                ('activate', models.BooleanField(default=True, verbose_name='Активировать')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='TargetSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Блок не пустой'), (1, 'Элементов меньше чем'), (2, 'Элементов больше чем'), (3, 'Содержит'), (4, 'Начинается с'), (5, 'Заканчивается')], default=0, verbose_name='Тип')),
                ('type_param', models.CharField(blank=True, max_length=255, verbose_name='Дополнительный параметр')),
                ('block', models.TextField(default='', verbose_name='Проверяемый блок')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='parser_app.targetsmodel', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайтов',
            },
        ),
    ]
