# Generated by Django 5.2.6 on 2025-10-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('parser_app', '0002_userperiodictasksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperiodictasksmodel',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_user', to='django_celery_beat.periodictask', verbose_name='Задача'),
        ),
    ]
