# Generated by Django 5.2.6 on 2025-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_targetsettingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsettingsmodel',
            name='message',
            field=models.TextField(default='', verbose_name='Test'),
            preserve_default=False,
        ),
    ]
