# Generated by Django 5.2.6 on 2025-09-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_targetsettingsmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsmodel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '--------'), (1, 'Успешно'), (2, 'Ошибка'), (3, 'Доступен')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='targetsmodel',
            name='status_changed',
            field=models.DateTimeField(default=None, null=True, verbose_name='Статус изменился'),
        ),
    ]
