# Generated by Django 5.2.6 on 2025-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_targetsmodel_status_targetsmodel_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsmodel',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Активировать'),
        ),
    ]
