# Generated by Django 5.2.6 on 2025-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_targetsmodel_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsmodel',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Простая'), (1, 'Сложная'), (2, 'Авито'), (3, 'Яндекс'), (4, 'Циан')], default=0, verbose_name='Тип'),
        ),
    ]
