# Generated by Django 5.2.6 on 2025-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_targetsmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsettingsmodel',
            name='block',
            field=models.TextField(default='', verbose_name='Проверяемый блок'),
        ),
        migrations.AddField(
            model_name='targetsettingsmodel',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Блок не пустой'), (1, 'Элементов меньше чем'), (2, 'Элементов больше чем')], default=0, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='targetsettingsmodel',
            name='type_param',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дополнительный параметр'),
        ),
    ]
