# Generated by Django 5.2.6 on 2025-10-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_alter_targetsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetsettingsmodel',
            name='message',
        ),
        migrations.AlterField(
            model_name='targetsettingsmodel',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Блок не пустой'), (1, 'Элементов меньше чем'), (2, 'Элементов больше чем'), (3, 'Содержит'), (4, 'Начинается с'), (5, 'Заканчивается')], default=0, verbose_name='Тип'),
        ),
    ]
