# Generated by Django 5.2.6 on 2025-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=100, verbose_name='id Телеграм')),
            ],
            options={
                'verbose_name': 'Телеграм аккаут',
                'verbose_name_plural': 'Телеграм аккауты',
            },
        ),
    ]
